# Site settings

title: Marian Reid
tag_text: Marian Reid
description: Communications Consultant and Storyteller
url: http://marianreid.com
author: Marian Reid


# Build settings

markdown: kramdown
exclude: ["README.md"]
gems:
- jekyll-seo-tag
# - jekyll-sitemap
sass:
  style: compressed
