# Site settings

title: Marian Reid
tag_text: Marian Reid
description: Communications Consultant and Storyteller
url: http://marianreid.com
author: Marian Reid

# Build settings
repository: hutchiko/marianreid.com
markdown: kramdown
exclude: ["README.md"]
gems:
- jekyll-seo-tag
- jekyll-sitemap
# - jekyll-cloudinary
sass:
  style: compressed


cloudinary:
  verbose: true
  cloud_name: hutchiko
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: "(min-width: 50rem) 50rem, 90vw"
